openapi: 3.0.3
info:
  description: "A simple API to interact with the Domain Slice Management Function.\
    \ Supports reserving, creating and removing slices and tunnels from one external\
    \ domain to another external domain or host. Please refer to the topology drawings\
    \ for further information about the network structures."
  title: DSMF
  version: 1.0.0
servers:
- url: "{protocol}://{apiRoot}/v1"
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    apiRoot:
      default: localhost:8081
      description: The server to use
paths:
  /auth:
    description: Endpoint to manage authentication tokens
    post:
      description: "Issues a new authentication token in exchange for credentials.\
        \ Currently requires no credentials, this is up to future implementations."
      operationId: auth_post
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: The authentication token as string
        "403":
          description: Wrong credentials were specified
      tags:
      - Authentication
      x-openapi-router-controller: dsmf_server.controllers.authentication_controller
    summary: Manages authentication towards this service
  /configuration:
    description: Endpoint to manage service configuration
    get:
      description: Fetch the current configuration of this service
      operationId: configuration_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/domain_configuration'
          description: The current configuration
        "403":
          description: Invalid authentication provided
      tags:
      - Configuration
      x-openapi-router-controller: dsmf_server.controllers.configuration_controller
    put:
      description: Installs a new configuration for this service
      operationId: configuration_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/domain_configuration'
        description: The configuration to install. Will check for issues.
        x-body-name: body
      responses:
        "200":
          description: The configuration has been installed
        "403":
          description: Invalid authentication provided
        "406":
          description: A value exceeds the allowed range
        "409":
          description: There are slices currently running. Reconfiguring is not supported
            while slices are open.
        "412":
          description: The provided configuration is invalid
      tags:
      - Configuration
      x-openapi-router-controller: dsmf_server.controllers.configuration_controller
      x-codegen-request-body-name: body
    summary: Manages the configuration of this service
  /slice_deployment:
    delete:
      description: Deletes a slice
      operationId: slice_deployment_delete
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the slice to be deleted.
        explode: true
        in: query
        name: slice_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The slice was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The slice could not be found.
      tags:
      - Slice Management
      x-openapi-router-controller: dsmf_server.controllers.slice_management_controller
    description: Endpoint to manage slices
    get:
      description: Lists all current slices
      operationId: slice_deployment_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/slice'
                type: array
          description: The current list of slices
        "403":
          description: Invalid authentication provided
      tags:
      - Slice Management
      x-openapi-router-controller: dsmf_server.controllers.slice_management_controller
    put:
      description: Creates a new slice from a reservation
      operationId: slice_deployment_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The slice to create from the corresponding reservation id
        explode: true
        in: query
        name: slice_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The slice has been created
        "403":
          description: Invalid authentication provided
        "404":
          description: The slice reservation could not be found.
        "500":
          description: The deployment to the network failed
      tags:
      - Slice Management
      x-openapi-router-controller: dsmf_server.controllers.slice_management_controller
    summary: Manages slices on the current domain
  /slice_reservation:
    delete:
      description: Deletes a slice reservation
      operationId: slice_reservation_delete
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the slice reservation to be deleted.
        explode: true
        in: query
        name: slice_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The slice reservation was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The slice reservation could not be found.
      tags:
      - Slice Reservation
      x-openapi-router-controller: dsmf_server.controllers.slice_reservation_controller
    description: Endpoint to manage slice reservations
    get:
      description: Lists all current slice reservations
      operationId: slice_reservation_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/slice'
                type: array
          description: The current list of slice reservations
        "403":
          description: Invalid authentication provided
      tags:
      - Slice Reservation
      x-openapi-router-controller: dsmf_server.controllers.slice_reservation_controller
    put:
      description: Creates a new slice reservation
      operationId: slice_reservation_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/slice'
        description: The slice to reserve. Will check for issues.
        x-body-name: body
      responses:
        "200":
          description: The slice has been reserved
        "403":
          description: Invalid authentication provided
        "404":
          description: The input or output could not be found
        "406":
          description: A value exceeds the allowed range
        "409":
          description: A slice with this id is already known
        "412":
          description: A value does not match the schema
        "507":
          description: Insufficient resources
      tags:
      - Slice Reservation
      x-openapi-router-controller: dsmf_server.controllers.slice_reservation_controller
      x-codegen-request-body-name: body
    summary: Manages slice reservations on the current domain
  /tunnel_deployment:
    delete:
      description: Deletes a tunnel
      operationId: tunnel_deployment_delete
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the tunnel to be deleted.
        explode: true
        in: query
        name: tunnel_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The tunnel was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The tunnel could not be found.
      tags:
      - Tunnel Management
      x-openapi-router-controller: dsmf_server.controllers.tunnel_management_controller
    description: Endpoint to manage tunnels
    get:
      description: Lists all current tunnels
      operationId: tunnel_deployment_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tunnel'
                type: array
          description: The current list of tunnels
        "403":
          description: Invalid authentication provided
      tags:
      - Tunnel Management
      x-openapi-router-controller: dsmf_server.controllers.tunnel_management_controller
    put:
      description: Creates a new tunnel or modifies a tunnel from a reservation
      operationId: tunnel_deployment_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The tunnel to create from the corresponding reservation id
        explode: true
        in: query
        name: tunnel_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The tunnel has been created
        "403":
          description: Invalid authentication provided
        "404":
          description: The tunnel reservation could not be found.
        "500":
          description: The deployment to the network failed
      tags:
      - Tunnel Management
      x-openapi-router-controller: dsmf_server.controllers.tunnel_management_controller
    summary: Manages tunnels on the current domain
  /tunnel_reservation:
    delete:
      description: Deletes a tunnel reservation
      operationId: tunnel_reservation_delete
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the tunnel reservation to be deleted.
        explode: true
        in: query
        name: tunnel_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The tunnel reservation was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The tunnel reservation could not be found.
      tags:
      - Tunnel Reservation
      x-openapi-router-controller: dsmf_server.controllers.tunnel_reservation_controller
    description: Endpoint to manage tunnel reservations
    get:
      description: Lists all current tunnel reservations
      operationId: tunnel_reservation_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tunnel'
                type: array
          description: The current list of tunnel reservations
        "403":
          description: Invalid authentication provided
      tags:
      - Tunnel Reservation
      x-openapi-router-controller: dsmf_server.controllers.tunnel_reservation_controller
    put:
      description: "Creates a new tunnel reservation or stages changes to an existing\
        \ deployed tunnel, as long as source and target of the tunnel match."
      operationId: tunnel_reservation_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tunnel'
        description: The tunnel to reserve. Will check for issues.
        x-body-name: body
      responses:
        "200":
          description: The tunnel has been reserved
        "403":
          description: Invalid authentication provided
        "404":
          description: The input or output could not be found
        "406":
          description: A value exceeds the allowed range
        "409":
          description: A tunnel with this id is already known and does not match current
            source and target
        "412":
          description: A value does not match the schema
        "507":
          description: Insufficient resources
      tags:
      - Tunnel Reservation
      x-openapi-router-controller: dsmf_server.controllers.tunnel_reservation_controller
      x-codegen-request-body-name: body
    summary: Manages tunnel reservations on the current domain
components:
  schemas:
    slice:
      example:
        tunnel_id: 2
        burst_rate: 5
        latency: 5
        max_rate: 1
        transport_protocol: UDP
        to:
          port: 7
          ip: ip
          name: name
          network: network
        fr:
          port: 7
          ip: ip
          name: name
          network: network
        min_rate: 6
        slice_id: 0
      properties:
        slice_id:
          description: The slice identifier
          format: int32
          title: slice_id
          type: integer
        min_rate:
          description: The minimum transmission rate as bits/s
          format: int64
          title: min_rate
          type: integer
        max_rate:
          description: The maximum transmission rate as bits/s
          format: int64
          title: max_rate
          type: integer
        burst_rate:
          description: The burst transmission rate as bits/s
          format: int64
          title: burst_rate
          type: integer
        latency:
          description: The required maximum latency
          format: int16
          title: latency
          type: integer
        tunnel_id:
          description: The tunnel identifier
          format: int32
          title: tunnel_id
          type: integer
        transport_protocol:
          description: The protocol to be expected
          enum:
          - UDP
          - TCP
          title: transport_protocol
          type: string
        fr:
          $ref: '#/components/schemas/endpoint'
        to:
          $ref: '#/components/schemas/endpoint'
      title: slice
      type: object
    tunnel:
      example:
        public_key: public_key
        tunnel_id: 0
        burst_rate: 5
        latency: 5
        max_rate: 1
        private_key: private_key
        to:
          port: 7
          ip: ip
          name: name
          network: network
        fr:
          port: 7
          ip: ip
          name: name
          network: network
        min_rate: 6
      properties:
        tunnel_id:
          description: The tunnel identifier
          format: int32
          title: tunnel_id
          type: integer
        min_rate:
          description: The minimum transmission rate as bits/s
          format: int64
          title: min_rate
          type: integer
        max_rate:
          description: The maximum transmission rate as bits/s
          format: int64
          title: max_rate
          type: integer
        burst_rate:
          description: The burst transmission rate as bits/s
          format: int64
          title: burst_rate
          type: integer
        latency:
          description: The required maximum latency
          format: int16
          title: latency
          type: integer
        fr:
          $ref: '#/components/schemas/endpoint'
        to:
          $ref: '#/components/schemas/endpoint'
        private_key:
          description: The tunnel private key
          title: private_key
          type: string
        public_key:
          description: The tunnel public key (of the other side)
          title: public_key
          type: string
      title: tunnel
      type: object
    endpoint:
      description: Specifying an endpoint to be matched for source or target
      example:
        port: 7
        ip: ip
        name: name
        network: network
      properties:
        ip:
          description: Specifies the source or target ip to be matched. Leave empty
            for no matching.
          title: ip
          type: string
        port:
          default: 0
          description: Specifies the source or target port to be matched. Leave empty
            or on 0 for no matching.
          format: i16
          title: port
          type: integer
        name:
          description: Specifies the name of this entry to look up in our configuration.
          title: name
          type: string
        network:
          description: Specifies the network name of this endpoint.
          title: network
          type: string
      title: endpoint
      type: object
    domain_configuration:
      description: The configuration for this service
      example:
        network_borders:
        - device_name: device_name
          network_name: network_name
          device_type: SWITCH
          connection:
            intf_name: intf_name
            other_end: other_end
            intf_id: 1
        - device_name: device_name
          network_name: network_name
          device_type: SWITCH
          connection:
            intf_name: intf_name
            other_end: other_end
            intf_id: 1
        vpn_gateways:
        - port: 6
          ip: localhost
          name: name
          dpid: 5
          connections:
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          network: network
        - port: 6
          ip: localhost
          name: name
          dpid: 5
          connections:
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          network: network
        switches:
        - port: 6
          ip: localhost
          name: name
          dpid: 5
          connections:
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          network: network
        - port: 6
          ip: localhost
          name: name
          dpid: 5
          connections:
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          - intf_name: intf_name
            other_end: other_end
            intf_id: 1
          network: network
        controllers:
        - port: 0
          ip: localhost
          name: name
        - port: 0
          ip: localhost
          name: name
        reservable_bitrate: 5
        type: DSMF
        networks:
        - subnet: subnet
          name: name
          preferred_vpn:
          - preferred_vpn
          - preferred_vpn
          reachable:
          - reachable
          - reachable
        - subnet: subnet
          name: name
          preferred_vpn:
          - preferred_vpn
          - preferred_vpn
          reachable:
          - reachable
          - reachable
        network: network
      properties:
        type:
          description: The service type to be used
          enum:
          - DSMF
          - DTMF
          title: type
          type: string
        network:
          description: Our network name
          title: network
          type: string
        controllers:
          description: Specifies the controllers available to us
          items:
            $ref: '#/components/schemas/controller_configuration'
          title: controllers
          type: array
        vpn_gateways:
          description: The vpn gateways known to us
          items:
            $ref: '#/components/schemas/device_configuration'
          title: vpn_gateways
          type: array
        switches:
          description: The switches known to us
          items:
            $ref: '#/components/schemas/device_configuration'
          title: switches
          type: array
        network_borders:
          description: The routes to other networks known to us
          items:
            $ref: '#/components/schemas/network_border_configuration'
          title: network_borders
          type: array
        networks:
          description: The other networks known to us
          items:
            $ref: '#/components/schemas/network_configuration'
          title: networks
          type: array
        reservable_bitrate:
          default: 1000000000
          description: The bitrate that can be reserved by hosts on our network
          format: i64
          title: reservable_bitrate
          type: integer
      title: domain_configuration
      type: object
    controller_configuration:
      description: A controller configuration element
      example:
        port: 0
        ip: localhost
        name: name
      properties:
        ip:
          default: localhost
          description: The ip or name the controller can be reached on
          title: ip
          type: string
        port:
          default: 8080
          description: The port that the controller REST API can be reached on
          format: i16
          title: port
          type: integer
        name:
          description: The name of this controller
          title: name
          type: string
      title: controller_configuration
      type: object
    device_configuration:
      description: A device/switch configuration element
      example:
        port: 6
        ip: localhost
        name: name
        dpid: 5
        connections:
        - intf_name: intf_name
          other_end: other_end
          intf_id: 1
        - intf_name: intf_name
          other_end: other_end
          intf_id: 1
        network: network
      properties:
        ip:
          default: localhost
          description: The ip or name the device can be reached on
          title: ip
          type: string
        port:
          default: 8082
          description: The port that the device REST API can be reached on
          format: i16
          title: port
          type: integer
        connections:
          description: The (relevant) interface definitions for this device
          items:
            $ref: '#/components/schemas/connection_configuration'
          title: connections
          type: array
        network:
          description: The network name this device is assigned to
          title: network
          type: string
        name:
          description: The name of the device
          title: name
          type: string
        dpid:
          description: The datapath id in case this is a switch
          format: i64
          title: dpid
          type: integer
      title: device_configuration
      type: object
    network_border_configuration:
      description: A network border configuration element (telling us where to route
        traffic to when wanting to reach a different network)
      example:
        device_name: device_name
        network_name: network_name
        device_type: SWITCH
        connection:
          intf_name: intf_name
          other_end: other_end
          intf_id: 1
      properties:
        network_name:
          description: The network this border leads to
          title: network_name
          type: string
        device_name:
          description: The name of the device that has a direct connection to the
            other network (our side)
          title: device_name
          type: string
        device_type:
          description: The type of the remote device
          enum:
          - SWITCH
          - VPN
          - HOST
          title: device_type
          type: string
        connection:
          $ref: '#/components/schemas/connection_configuration'
      title: network_border_configuration
      type: object
    connection_configuration:
      description: A connection configuration element
      example:
        intf_name: intf_name
        other_end: other_end
        intf_id: 1
      properties:
        intf_name:
          description: The name of the interface on a switch
          title: intf_name
          type: string
        intf_id:
          description: The id of the interface
          format: i16
          title: intf_id
          type: integer
        other_end:
          description: The name of the device on the other side
          title: other_end
          type: string
      title: connection_configuration
      type: object
    network_configuration:
      description: A network configuration element
      example:
        subnet: subnet
        name: name
        preferred_vpn:
        - preferred_vpn
        - preferred_vpn
        reachable:
        - reachable
        - reachable
      properties:
        name:
          description: The name of the network
          title: name
          type: string
        reachable:
          description: Networks reachable from this network
          items:
            type: string
          title: reachable
          type: array
        preferred_vpn:
          description: VPN gateways to use (in order) to connect to this network
          items:
            type: string
          title: preferred_vpn
          type: array
        subnet:
          description: Subnet of this network
          title: subnet
          type: string
      title: network_configuration
      type: object
